{{- if .Values.masterKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.masterKeySecretName }}
  namespace: {{ include "csi-secret-age.namespace" . }}
  labels:
    {{- include "csi-secret-age.labels" . | nindent 4 }}
stringData:
  key.txt: {{ .Values.masterKey | quote }}
{{- end }}
