{{- if .Values.awsKms }}
{{- if .Values.awsKms.ciphertext }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.awsKms.secretName | default "age-aws-kms-ciphertext" }}
  namespace: {{ include "csi-secret-age.namespace" . }}
  labels:
    {{- include "csi-secret-age.labels" . | nindent 4 }}
stringData:
  ciphertext: {{ .Values.awsKms.ciphertext | quote }}
{{- end }}
{{- end }}
{{- if .Values.gcpKms }}
{{- if .Values.gcpKms.keyName }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gcpKms.keySecretName | default "age-gcp-kms-key" }}
  namespace: {{ include "csi-secret-age.namespace" . }}
  labels:
    {{- include "csi-secret-age.labels" . | nindent 4 }}
stringData:
  keyName: {{ .Values.gcpKms.keyName | quote }}
{{- end }}
{{- if .Values.gcpKms.ciphertext }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gcpKms.ciphertextSecretName | default "age-gcp-kms-ciphertext" }}
  namespace: {{ include "csi-secret-age.namespace" . }}
  labels:
    {{- include "csi-secret-age.labels" . | nindent 4 }}
stringData:
  ciphertext: {{ .Values.gcpKms.ciphertext | quote }}
{{- end }}
{{- end }}
