{{- if .Values.jwtPublicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jwtPublicKeySecretName }}
  namespace: {{ include "csi-secret-age.namespace" . }}
  labels:
    {{- include "csi-secret-age.labels" . | nindent 4 }}
stringData:
  jwt-public-key.pem: |
    {{- .Values.jwtPublicKey | nindent 4 }}
{{- end }}
