apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ include "csi-secret-age.namespace" . }}
  labels:
    {{- include "csi-secret-age.labels" . | nindent 4 }}
